--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKING_3
--------------------------------------------------------
CREATE SEQUENCE booking_seq
START WITH 1
INCREMENT BY 1;

  CREATE TABLE "MBC"."BOOKING_3" 
   (   "TABLENUM" NUMBER(7,0), 
   "STORECODE" NUMBER(7,0), 
   "ID" VARCHAR2(20 BYTE), 
   "SARAMSU" NUMBER(3,0), 
   "STATE" VARCHAR2(10 BYTE), 
   "BOOKINGDATE" DATE, 
   "BOOKINGTIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MBC.BOOKING_3
SET DEFINE OFF;
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (22,30,'testuser',1,'대기',to_date('25/05/23','RR/MM/DD'),'15:32');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (36,28,'appple01',2,'대기',to_date('25/05/16','RR/MM/DD'),'11:59');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (24,28,'testuser',2,'대기',to_date('25/05/08','RR/MM/DD'),'19:50');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (27,24,'testuser',1,'대기',to_date('25/05/23','RR/MM/DD'),'15:37');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (63,32,'korea',5,'대기',to_date('25/05/14','RR/MM/DD'),'19:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (28,23,'testuser',2,'대기',to_date('25/06/04','RR/MM/DD'),'19:39');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (42,30,'appple01',9,'예약중',to_date('25/05/22','RR/MM/DD'),'18:55');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (40,30,'mitt12',3,'예약중',to_date('25/05/23','RR/MM/DD'),'23:02');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (37,12,'appple01',1,'대기',to_date('25/04/29','RR/MM/DD'),'11:56');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (64,23,'korea',2,'대기',to_date('25/06/05','RR/MM/DD'),'16:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (65,1,'korea',6,'대기',to_date('25/05/31','RR/MM/DD'),'19:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (43,25,'appple01',1,'예약중',to_date('25/05/23','RR/MM/DD'),'18:54');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (41,27,'mitt12',1,'대기',to_date('25/06/19','RR/MM/DD'),'03:01');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (44,23,'appple01',1,'대기',to_date('25/05/08','RR/MM/DD'),'18:55');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (66,4,'mitskgy123',2,'대기',to_date('25/05/23','RR/MM/DD'),'12:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (46,30,'testuser',1,'대기',to_date('25/05/22','RR/MM/DD'),'16:55');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (47,30,'testuser',2,'대기',to_date('25/05/24','RR/MM/DD'),'11:30');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (67,28,'mitskgy123',3,'대기',to_date('25/05/31','RR/MM/DD'),'15:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (68,30,'mitskgy123',4,'대기',to_date('25/05/21','RR/MM/DD'),'19:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (50,7,'appple01',9,'예약중',to_date('25/05/21','RR/MM/DD'),'18:30');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (61,36,'appple01',2,'대기',to_date('25/06/07','RR/MM/DD'),'17:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (62,7,'korea',2,'대기',to_date('25/06/12','RR/MM/DD'),'11:30');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (69,27,'mitskgy123',2,'대기',to_date('25/05/14','RR/MM/DD'),'14:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (70,19,'mmss',5,'대기',to_date('25/05/07','RR/MM/DD'),'13:00');
Insert into MBC.BOOKING_3 (TABLENUM,STORECODE,ID,SARAMSU,STATE,BOOKINGDATE,BOOKINGTIME) values (71,15,'siu123',2,'대기',to_date('25/06/27','RR/MM/DD'),'17:30');
--------------------------------------------------------
--  DDL for Index PK_BOOKING_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "MBC"."PK_BOOKING_3" ON "MBC"."BOOKING_3" ("TABLENUM", "STORECODE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOKING_3
--------------------------------------------------------

  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "PK_BOOKING_3" PRIMARY KEY ("TABLENUM", "STORECODE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("STORECODE" NOT NULL ENABLE);
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("TABLENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKING_3
--------------------------------------------------------

  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "FK_MEMBER_3_TO_BOOKING_3_1" FOREIGN KEY ("ID")
     REFERENCES "MBC"."MEMBER_3" ("ID") ENABLE;
  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "FK_STORE_3_TO_BOOKING_3_1" FOREIGN KEY ("STORECODE")
     REFERENCES "MBC"."STORE_3" ("STORECODE") ENABLE;
