
  CREATE TABLE "MBC"."MEMBER_LIKES" 
   (   "MEMBER_ID" VARCHAR2(20 BYTE), 
   "STORECODE" NUMBER(7,0), 
   "LIKED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT "UNQ_MEMBER_STORE" UNIQUE ("MEMBER_ID", "STORECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
    CONSTRAINT "FK_MEMBER" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "MBC"."MEMBER_3" ("ID") ENABLE, 
    CONSTRAINT "FK_STORE" FOREIGN KEY ("STORECODE")
     REFERENCES "MBC"."STORE_3" ("STORECODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

